version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: test
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - parental_control_network

  server:
    build: .
    container_name: parental_control_server
    restart: always
    ports:
      - "8765:8765"
    environment:
      MONGODB_URL: mongodb://admin:admin123@mongodb:27017
      MONGODB_DB_NAME: parental_control
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8765
      DEBUG: "True"
    depends_on:
      - mongodb
    networks:
      - parental_control_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8765 --reload

volumes:
  mongodb_data:

networks:
  parental_control_network:
    driver: bridge
